import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('@123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user2@example.com',
      password: bcrypt.hashSync('@123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Energizer Battery',
      slug: 'free-Battery1',
      category: 'Battery',
      image: '/images/Battery.jpeg',
      price: 70,
      brand: 'Energizer',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'high quality product',
      isFeatured: true,
      banner: '/images/batteryBanner.png',
    },
    {
      name: 'Chloride Battery',
      slug: 'free-Battery2',
      category: 'Battery',
      image: '/images/chloride-battery.jpeg',
      price: 80,
      brand: 'Battery',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'PowerLine Battery',
      slug: 'free-Battery3',
      category: 'Battery',
      image: '/images/powerline-battery.jpeg',
      price: 120,
      brand: 'PowerLine',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'Magnum Shock Absorber',
      slug: 'best-shock-absorber1',
      category: 'Suspension',
      image: '/images/shocks.jpeg',
      price: 120,
      brand: 'Magnum',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'muffler',
      slug: 'muffler',
      category: 'exhaust',
      image: '/images/muffler.jpeg',
      price: 1200,
      brand: 'juakali',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'Coil Spring',
      slug: 'coil-spring',
      category: 'Suspension',
      image: '/images/spring.png',
      price: 1200,
      brand: 'juakali',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'Champion Windscreen Wiper',
      slug: 'wiper1',
      category: 'Wipers',
      image: '/images/wiperChamp.jpeg',
      price: 1200,
      brand: 'Champion',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
      isFeatured: true,
      banner: '/images/wiperBanner.jpeg',
    },
    {
      name: 'Bosch Windscreen Wiper',
      slug: 'wiper2',
      category: 'Wipers',
      image: '/images/wiperBosch.jpeg',
      price: 1200,
      brand: 'Bosch',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
  ],
};

export default data;
